{% set name = "maml" %}
{% set version = "2024.6.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/maml-{{ version }}.tar.gz
  sha256: 7902e00973a5ef1143b783e7ef8c0fa1dad8c4cd73b621a86b440af0ab36c042

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=43.0.0
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - scipy
    - monty
    - scikit-learn
    - pandas
    - pymatgen
    - tqdm

test:
  imports:
    - maml
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://materialsvirtuallab.github.io/maml
  summary: maml is a machine learning library for materials science.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
