{% set name = "maml" %}
{% set version = "2022.1.28" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/materialsvirtuallab/maml/archive/refs/tags/v{{ version }}.tar.gz
  sha256: d3fb093979ee625ec81281d75dd8c98d601a074a4a31ebdc634b198ea1b394c3

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - keras
    - monty
    - numpy
    - pandas
    - pymatgen
    - python >=3.5
    - scikit-learn
    - scipy
    - tensorflow
    - cvxpy

test:
  imports:
    - maml
    - maml.apps
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/materialsvirtuallab/maml
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Python for Materials Machine Learning, Materials Descriptors, Machine Learning Force Fields, Deep Learning, etc.'
  description: |
    maml (MAterials Machine Learning) is a Python package that 
    aims to provide useful high-level interfaces that make ML 
    for materials science as easy as possible.
    The goal of maml is not to duplicate functionality already
    available in other packages. maml relies on well-established
    packages such as scikit-learn and tensorflow for 
    implementations of ML algorithms, as well as other materials
    science packages such as pymatgen and matminer for crystal/
    molecule manipulation and feature generation.
  doc_url: http://maml.ai/index.html
  dev_url: https://github.com/materialsvirtuallab/maml

extra:
  recipe-maintainers:
    - jan-janssen
