{% set name = "maml" %}
{% set version = "2022.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/materialsvirtuallab/maml/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 4df0d4abf8ae84f18fa008dd5334f3bd0656c12a30fbce6336d1344b7d6db6e3

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - python >=3.5
    - numpy =1.22.3
    - scipy =1.7.3
    - pymatgen =2022.3.7
    - monty =2022.3.12
    - pandas =1.4.1
    - scikit-learn =1.0.2
    - h5py =3.6.0
    - joblib =1.1.0
    - tqdm =4.63.0
    - pymongo =4.0.1

test:
  imports:
    - maml
    - maml.apps
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/materialsvirtuallab/maml
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python for Materials Machine Learning, Materials Descriptors, Machine Learning Force Fields, Deep Learning, etc.
  description: |
    maml (MAterials Machine Learning) is a Python package that 
    aims to provide useful high-level interfaces that make ML 
    for materials science as easy as possible.
    The goal of maml is not to duplicate functionality already
    available in other packages. maml relies on well-established
    packages such as scikit-learn and tensorflow for 
    implementations of ML algorithms, as well as other materials
    science packages such as pymatgen and matminer for crystal/
    molecule manipulation and feature generation.
  doc_url: http://maml.ai/index.html
  dev_url: https://github.com/materialsvirtuallab/maml

extra:
  recipe-maintainers:
    - jan-janssen
