{% set name = "maml" %}
{% set version = "2025.4.3" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/maml-{{ version }}.tar.gz
  sha256: 3ad97ab5b7a4db4dbb1840e0200686e476fdb380b1515765137852d59a49b9a8

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=43.0.0
    - pip
  run:
    - mp-api
    - python >={{ python_min }}
    - numpy
    - scipy
    - monty
    - scikit-learn >=1.6.1
    - pandas
    - pymatgen
    - tqdm

test:
  imports:
    - maml
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://materialsvirtuallab.github.io/maml
  summary: maml is a machine learning library for materials science.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
