{% set name = "maml" %}
{% set version = "2023.9.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/maml-{{ version }}.tar.gz
  sha256: 163e19da32f32ea65377b434a11dcf7529e1e676c5585518d0af447dae2a2a4d

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python
  number: 0

requirements:
  host:
    - python >=3.5
    - numpy >=1.18,<1.20  # [py<39]
    - setuptools >=43.0.0
    - pip
  run:
    - python >=3.5
    - numpy
    - scipy
    - monty
    - scikit-learn
    - pandas
    - pymatgen
    - tqdm

test:
  imports:
    - maml
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://materialsvirtuallab.github.io/maml
  summary: maml is a machine learning library for materials science.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
